version : '3'
services:
  uaspemmob:
    build: ./php
    image: uaspemmob_php:latest
    container_name: uaspemmob
    hostname: "uaspemmob"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_uas
  db_uas:
    image: mariadb:10.2
    container_name: db_uas
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: djambred
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx_uaspemmob:
    build: ./nginx
    image: nginx_uaspemmob:latest
    container_name: nginx_uaspemmob
    hostname: "nginx_uaspemmob"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - uaspemmob